name: Build, Test and Deploy Library App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install
    - name: Start the Backend
      run: npm run start-be &
    - name: Start the FrontEnd
      run: npm run start-fe &
    - name: Execute UI Test
      run: npm run test
